### ISSUE TITLE
Publish-Interactive.ps1 in output missing when using MSBuild

### ISSUE THREAD

**Issue by robertmuehsig** [sayedihashimi/package-web#27]
We have a custom TFS BuildProcess and use MSBuild to create the MSDeploy Package, but this problem occurres also on my local machine. 

The MSBuild CMD for building the package is just like that:

msbuild MyWebProject.csproj /t:Package /p:Configuration=Release /p:Platform="Any CPU" /p:PackageLocation=E:\Output_Release\Web.zip /p:OutputPath=E:\Temp\

Problem: The output folder only contains the normal web-deploy files:
Web.deploy-readme.txt
Web.deploy.cmd
Web.SetParameters.xml
Web.SourceManifest.xml
Web.zip

But the Publish-Interactive.ps1 is missing. If I publish it via VisualStudio than I get the file.

On my local machine I get this warning in the build output:
Build succeeded.

E:..._Package\Sedodream.Package.targets(33,57): warning MSB4057: 
The target "CopyPipelineFiles" does not exist in the project.

1 Warning(s)

On TFS I get this warnings:

$/.../_Package/Sedodream.Package.targets - 0 error(s), 2 warning(s)
 C:..._Package\Sedodream.Package.targets (33): 
The target CopyAllFilesToSingleFolderForMsdeploy" does not exist in the project.
 C:..._Package\Sedodream.Package.targets (33): 
The target "CopyPipelineFiles" does not exist in the project.

Any idea?

**Comment by sayedihashimi** [comment]
I will take a look tonight to see what is happening here.

**Comment by sayedihashimi** [comment]
I think I figured it out. The .ps1 file was not being copied because I was not using the correct MSBuild property, so the script didn't know where to copy it. Can you try it out and let me know if it resolves the issue for you?

In a project which already has PackageWeb installed there is a _Package folder. Inside that folder replace the Sedodream.Package.targets file with the contents at https://raw.github.com/sayedihashimi/package-web/master/Nuget/Sedodream.Package.targets. After that close VS, try your build again and let me know.

After we verify that this is the correct fix I will correct the warning regarding the CopyAllFilesToSingleFolderForMsdeploy target, and then update the NuGet package.

Thanks in advance for you help here.

**Comment by robertmuehsig** [comment]
This solves the problem! Thanks!
