### ISSUE TITLE
Username value is not being passed to the MSDeploy command

### ISSUE THREAD

**Issue by tbehunin** [sayedihashimi/package-web#37]
When executing PublishInteractive.ps1, one of the user input fields is Username. After entering that field, the Powershell script executes the MSDeploy command, but the username key/value pair is missing (the password key/value are present though). On line 385 of the PublishInteractive.ps1 file, we see the following lines:

```
$userNameParamValue = FindParamByName -allParams $paramValues -name $paramNameUsername
$usernameCommandFrag = ""
if($userNameParamValue.length -gt 0){
    $usernameCommandFrag = ",Username={0}" -f $userNameParamValue.Value
}

$passwordParamvalue = ($paramValues | Where-Object{$_.name -eq "Password"}).Value
$passwordCommandFrag = ""
if($passwordParamvalue.length -gt 0) {
    $passwordCommandFrag = ",Password={0}" -f $passwordParamvalue
}
```

There is a difference in the way it's retrieving the value of the username with the value of the password - possibly the source of the bug. Is that by design?

**Comment by tbehunin** [comment]
Think I found the fix. Line 387 should not be checking the length of the OBJECT being returned. Instead, it should read:

if($userNameParamValue){

**Comment by sayedihashimi** [comment]
I wasn't able to repro your issue. Both username and password were being passed into the command line.

Thanks for letting me know that the param values were not being retrieved in a consistent manner. I have updated the code so that parameters are extracted in a uniform way. I just published 1.1.8.2 to nuget.org.

Can you try with the latest version and re-open this if you are still having issues?

**Comment by tbehunin** [comment]
Looks like this version fixed the issue. After you changed line 386 to assign the string ".Value" from the object returned in FindParamByName, $userNameParamValue.length (on line 388) worked as expected, since the variable type is now of type String (vs an object, which was what it was before).

**Comment by sayedihashimi** [comment]
OK great glad to hear things are working. Thanks for reporting this let me know if you have any issues going forward.

**Comment by tbehunin** [comment]
Can't wait for Issue #34 to get completed! :)

**Comment by sayedihashimi** [comment]
#34 will take some time.
Currently the approach that PackageWeb uses is to extract out the .zip file
to a temp folder, perform the transforms in that location. After that
msdeploy.exe is called with that folder as the ArchiveDir.
Since we want to avoid expanding out the entire package I'll have to change
it to: identify transforms w/o extracting any files, extract selected
transform, perform the transform, copy the .zip file, update the web.config
in the .zip file and then kick off msdeploy.exe.

It may be a bit before I can get to that. I will need to block some
dedicated time just for this.
